version: 2
jobs:
  build-and-test:
    docker:
      - image: cimg/rust:1.73

    services:
      - name: postgres
        image: cimg/postgres:14
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    environment:
      # Fail the build if there are warnings
      RUSTFLAGS: '-D warnings'
      CARGO_TERM_COLOR: always
      SQLX_VERSION: 0.7.1
      SQLX_FEATURES: "rustls,postgres"

    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      # If you have committed your Cargo.lock file to version control
      # delete this step.
      # - run:
      #     name: Calculate dependencies
      #     command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}-${SQLX_VERSION}
      - install_sqlx_cli:
          command: cargo install sqlx-cli --version=${SQLX_VERSION} --features=${SQLX_FEATURES} --no-default-features --locked

      - install_postgres_client:
          command: sudo apt update && sudo apt install postgresql-client -y

      - migrate_database:
          command: SKIP_DOCKER=true ./scripts/init_db.sh

      - run:
          name: Build all targets
          command: cargo build
      - save_cache:
          paths:
            - /home/circleci/.cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}-${SQLX_VERSION}
      - run:
          name: Run all tests
          command: cargo test

  # security:
  #   docker:
  #     - image: cimg/rust:1.73
  #   steps:
  #     - checkout
  #     - run:
  #         name: Version information
  #         command: rustc --version; cargo --version; rustup --version
  #     - run:
  #         name: Cache permission
  #         command: |
  #           sudo chown -R $(whoami):$(id -ng) /home/circleci/.cargo/bin/cargo
  #     - restore_cache:
  #         keys:
  #           - v1-cargo-audit-{{ arch }}
  #     - run:
  #         name: Install dependency auditing tool
  #         command: cargo install cargo-audit
  #     - save_cache:
  #         paths:
  #           - /home/circleci/.cargo/bin/cargo
  #         key: v1-cargo-audit-{{ arch }}
  #     - run:
  #         name: Check for known security issues in dependencies
  #         command: cargo audit

  format:
    docker:
      - image: cimg/rust:1.73
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install formatter
          command: rustup component add rustfmt
      - run:
          name: Formatting
          command: cargo fmt --all -- --check

  lint:
    docker:
      - image: cimg/rust:1.73
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install Clippy
          command: rustup component add clippy
      - run:
          name: Linting
          command: cargo clippy -- -D warnings

  coverage:
    machine: true
    steps:
      - checkout
      - run:
          name: Coverage with docker
          command: docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin cargo tarpaulin --ignore-tests

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      # - security:
      #     filters:
      #       tags:
      #         only: /.*/
      # - format:
      #     filters:
      #       tags:
      #         only: /.*/
      # - lint:
      #     filters:
      #       tags:
      #         only: /.*/
      # - coverage:
      #     filters:
      #       tags:
      #         only: /.*/
