application:
  port: 8000
  hmac_secret: 'some-very-long-and-secret-token'
database:
  host: "127.0.0.1"
  port: "5432"
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "http://localhost"
  sender_email: "rjh.hoffmann@gmail.com"
  authorization_token: "super-secret-token"
  timeout_milliseconds: 10000