application:
  port: 8000
  hmac_secret: "9d20c3c1f6a7b9f1e1cdefghijklmnop1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
database:
  host: "127.0.0.1"
  port: "5432"
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "http://localhost"
  sender_email: "rjh.hoffmann@gmail.com"
  authorization_token: "super-secret-token"
  timeout_milliseconds: 10000